"""init

Revision ID: 8049b66d8171
Revises: 
Create Date: 2025-12-27 22:52:06.680086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8049b66d8171'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_experiment_type_time', 'events', ['experiment_id', 'type', 'timestamp'], unique=False)
    op.create_index('ix_events_experiment_user_time', 'events', ['experiment_id', 'user_id', 'timestamp'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('traffic_allocation', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'key', name='uq_variant_experiment_key')
    )
    op.create_index('ix_variants_experiment_id', 'variants', ['experiment_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'user_id', name='uq_assignment_experiment_user')
    )
    op.create_index('ix_assignments_experiment_user', 'assignments', ['experiment_id', 'user_id'], unique=False)
    op.create_index('ix_assignments_experiment_variant_time', 'assignments', ['experiment_id', 'variant_id', 'assigned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_experiment_variant_time', table_name='assignments')
    op.drop_index('ix_assignments_experiment_user', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_variants_experiment_id', table_name='variants')
    op.drop_table('variants')
    op.drop_index('ix_events_experiment_user_time', table_name='events')
    op.drop_index('ix_events_experiment_type_time', table_name='events')
    op.drop_table('events')
    op.drop_table('experiments')
    # ### end Alembic commands ###
